#!/usr/bin/env python3
import subprocess
import sys
import os

def main(args):
  inf_name = args[0]
  out_name = "S/" + os.path.basename(inf_name) + ".s"
  cmd = ["clang", "--sysroot",
         "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS6.1.sdk",
         "-target", "armv7-ios", "-S", "-o-", args[0]]
  with open(out_name, "w") as outf:
    subprocess.check_call(cmd, stdout=outf)
  print(open(out_name).read())

if __name__ == "__main__":
  main(sys.argv[1:])
